//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public int Emp_Age { get; set; }
        public string Emp_DOB { get; set; }
        public string Emp_Gender { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_Phone { get; set; }
        public string Emp_Photo { get; set; }
        public string Emp_Qualification { get; set; }
        public string Emp_Marks { get; set; }
        public string Emp_Skills { get; set; }
        public string Emp_Experience { get; set; }
    }
}
